from flask_sqlalchemy import SQLAlchemy

DB = SQLAlchemy()

class Listing(DB.Model):
    __tablename__ = 'listings'
    """listing table columns"""
    id = DB.Column(DB.Integer, primary_key=True)
    host_response_time = DB.Column(DB.String(50), nullable=False)
    host_response_rate = DB.Column(DB.Float, nullable=False)
    host_is_superhost = DB.Column(DB.Float, nullable=False)
    host_listings_count = DB.Column(DB.Float, nullable=False)
    host_identity_verified = DB.Column(DB.Float, nullable=False)
    market = DB.Column(DB.String(50), nullable=False)
    latitude = DB.Column(DB.Float, nullable=False)
    longitude = DB.Column(DB.Float, nullable=False)
    property_type = DB.Column(DB.String(50), nullable=False)
    room_type = DB.Column(DB.String(50), nullable=False)
    accommodates = DB.Column(DB.Integer, nullable=False)
    bathrooms = DB.Column(DB.Float, nullable=False)
    bedrooms = DB.Column(DB.Float, nullable=False)
    beds = DB.Column(DB.Float, nullable=False)
    price = DB.Column(DB.Float, nullable=False)
    security_deposit = DB.Column(DB.Float, nullable=False)
    cleaning_fee = DB.Column(DB.Float, nullable=False)
    guests_included = DB.Column(DB.Integer, nullable=False)
    extra_people = DB.Column(DB.Float, nullable=False)
    minimum_nights = DB.Column(DB.Integer, nullable=False)
    maximum_nights = DB.Column(DB.Integer, nullable=False)
    availability_30 = DB.Column(DB.Integer, nullable=False)
    availability_365 = DB.Column(DB.Integer, nullable=False)
    number_of_reviews = DB.Column(DB.Integer, nullable=False)
    review_scores_rating = DB.Column(DB.Float, nullable=False)
    review_scores_accuracy = DB.Column(DB.Float, nullable=False)
    review_scores_cleanliness = DB.Column(DB.Float, nullable=False)
    review_scores_checkin = DB.Column(DB.Float, nullable=False)
    review_scores_communication = DB.Column(DB.Float, nullable=False)
    review_scores_location = DB.Column(DB.Float, nullable=False)
    review_scores_value = DB.Column(DB.Float, nullable=False)
    instant_bookable = DB.Column(DB.Integer, nullable=False)
    cancellation_policy = DB.Column(DB.String(50), nullable=False)
    calculated_host_listings_count = DB.Column(DB.Integer, nullable=False)
    calculated_host_listings_count_private_rooms = DB.Column(DB.Integer, nullable=False)
    reviews_per_month = DB.Column(DB.Float, nullable=False)
    years_as_host = DB.Column(DB.Integer, nullable=False)
    num_host_verifications = DB.Column(DB.Integer, nullable=False)